/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'doctorId' : Principal,
  'patientId' : Principal,
  'dateTime' : Time,
  'reason' : string,
}
export interface BasicPatientInfo {
  'age' : bigint,
  'bloodType' : [] | [string],
  'name' : string,
  'gender' : Gender,
  'phone' : string,
  'existingConditions' : Array<string>,
  'allergies' : Array<string>,
}
export interface DiagnosisRecord {
  'id' : string,
  'isEmergency' : boolean,
  'doctorNotes' : [] | [string],
  'patientId' : Principal,
  'conditionName' : string,
  'treatmentAdvice' : string,
  'confidenceScore' : bigint,
  'consultationRecommended' : boolean,
  'imageRef' : ExternalBlob,
  'timestamp' : Time,
  'severity' : Severity,
  'otcMedicines' : Array<string>,
}
export interface DiagnosticResult {
  'isEmergency' : boolean,
  'conditionName' : string,
  'treatmentAdvice' : string,
  'confidenceScore' : bigint,
  'consultationRecommended' : boolean,
  'severity' : Severity,
  'otcMedicines' : Array<string>,
}
export interface DoctorProfile {
  'bio' : string,
  'name' : string,
  'specialty' : string,
  'approved' : boolean,
  'availableSlots' : Array<Time>,
  'licenseNumber' : string,
}
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export interface MedicalHistoryEntry { 'notes' : string, 'timestamp' : Time }
export interface PatientProfile {
  'info' : BasicPatientInfo,
  'medicalHistory' : Array<MedicalHistoryEntry>,
}
export type Severity = { 'low' : null } |
  { 'emergency' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMedicalHistoryEntry' : ActorMethod<[MedicalHistoryEntry], undefined>,
  'analyze' : ActorMethod<[ExternalBlob], DiagnosticResult>,
  'approveDoctor' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[Appointment], undefined>,
  'createOrUpdateDoctorProfile' : ActorMethod<[DoctorProfile], undefined>,
  'createOrUpdatePatientProfile' : ActorMethod<[PatientProfile], undefined>,
  'getAllDiagnoses' : ActorMethod<[bigint, bigint], Array<DiagnosisRecord>>,
  'getApprovedDoctors' : ActorMethod<[], Array<DoctorProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [BasicPatientInfo]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalPatients' : bigint,
      'totalDiagnoses' : bigint,
      'emergencyCases' : bigint,
      'pendingDoctors' : bigint,
    }
  >,
  'getDiagnosisById' : ActorMethod<[string], DiagnosisRecord>,
  'getDoctorAppointments' : ActorMethod<[bigint, bigint], Array<Appointment>>,
  'getMedicalHistory' : ActorMethod<[], Array<MedicalHistoryEntry>>,
  'getOwnPatientProfile' : ActorMethod<[], PatientProfile>,
  'getPatientAppointments' : ActorMethod<[bigint, bigint], Array<Appointment>>,
  'getPatientDiagnoses' : ActorMethod<[bigint, bigint], Array<DiagnosisRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [BasicPatientInfo]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectDoctor' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[BasicPatientInfo], undefined>,
  'submitDiagnosis' : ActorMethod<[DiagnosisRecord], undefined>,
  'updateDoctorNotes' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];