/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const MedicalHistoryEntry = IDL.Record({
  'notes' : IDL.Text,
  'timestamp' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'emergency' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const DiagnosticResult = IDL.Record({
  'isEmergency' : IDL.Bool,
  'conditionName' : IDL.Text,
  'treatmentAdvice' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'consultationRecommended' : IDL.Bool,
  'severity' : Severity,
  'otcMedicines' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Appointment = IDL.Record({
  'doctorId' : IDL.Principal,
  'patientId' : IDL.Principal,
  'dateTime' : Time,
  'reason' : IDL.Text,
});
export const DoctorProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'specialty' : IDL.Text,
  'approved' : IDL.Bool,
  'availableSlots' : IDL.Vec(Time),
  'licenseNumber' : IDL.Text,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const BasicPatientInfo = IDL.Record({
  'age' : IDL.Nat,
  'bloodType' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'gender' : Gender,
  'phone' : IDL.Text,
  'existingConditions' : IDL.Vec(IDL.Text),
  'allergies' : IDL.Vec(IDL.Text),
});
export const PatientProfile = IDL.Record({
  'info' : BasicPatientInfo,
  'medicalHistory' : IDL.Vec(MedicalHistoryEntry),
});
export const DiagnosisRecord = IDL.Record({
  'id' : IDL.Text,
  'isEmergency' : IDL.Bool,
  'doctorNotes' : IDL.Opt(IDL.Text),
  'patientId' : IDL.Principal,
  'conditionName' : IDL.Text,
  'treatmentAdvice' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'consultationRecommended' : IDL.Bool,
  'imageRef' : ExternalBlob,
  'timestamp' : Time,
  'severity' : Severity,
  'otcMedicines' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMedicalHistoryEntry' : IDL.Func([MedicalHistoryEntry], [], []),
  'analyze' : IDL.Func([ExternalBlob], [DiagnosticResult], []),
  'approveDoctor' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func([Appointment], [], []),
  'createOrUpdateDoctorProfile' : IDL.Func([DoctorProfile], [], []),
  'createOrUpdatePatientProfile' : IDL.Func([PatientProfile], [], []),
  'getAllDiagnoses' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(DiagnosisRecord)],
      ['query'],
    ),
  'getApprovedDoctors' : IDL.Func([], [IDL.Vec(DoctorProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(BasicPatientInfo)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalPatients' : IDL.Nat,
          'totalDiagnoses' : IDL.Nat,
          'emergencyCases' : IDL.Nat,
          'pendingDoctors' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getDiagnosisById' : IDL.Func([IDL.Text], [DiagnosisRecord], ['query']),
  'getDoctorAppointments' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getMedicalHistory' : IDL.Func([], [IDL.Vec(MedicalHistoryEntry)], ['query']),
  'getOwnPatientProfile' : IDL.Func([], [PatientProfile], ['query']),
  'getPatientAppointments' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getPatientDiagnoses' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(DiagnosisRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BasicPatientInfo)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectDoctor' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([BasicPatientInfo], [], []),
  'submitDiagnosis' : IDL.Func([DiagnosisRecord], [], []),
  'updateDoctorNotes' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const MedicalHistoryEntry = IDL.Record({
    'notes' : IDL.Text,
    'timestamp' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'emergency' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const DiagnosticResult = IDL.Record({
    'isEmergency' : IDL.Bool,
    'conditionName' : IDL.Text,
    'treatmentAdvice' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'consultationRecommended' : IDL.Bool,
    'severity' : Severity,
    'otcMedicines' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'doctorId' : IDL.Principal,
    'patientId' : IDL.Principal,
    'dateTime' : Time,
    'reason' : IDL.Text,
  });
  const DoctorProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'specialty' : IDL.Text,
    'approved' : IDL.Bool,
    'availableSlots' : IDL.Vec(Time),
    'licenseNumber' : IDL.Text,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const BasicPatientInfo = IDL.Record({
    'age' : IDL.Nat,
    'bloodType' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'gender' : Gender,
    'phone' : IDL.Text,
    'existingConditions' : IDL.Vec(IDL.Text),
    'allergies' : IDL.Vec(IDL.Text),
  });
  const PatientProfile = IDL.Record({
    'info' : BasicPatientInfo,
    'medicalHistory' : IDL.Vec(MedicalHistoryEntry),
  });
  const DiagnosisRecord = IDL.Record({
    'id' : IDL.Text,
    'isEmergency' : IDL.Bool,
    'doctorNotes' : IDL.Opt(IDL.Text),
    'patientId' : IDL.Principal,
    'conditionName' : IDL.Text,
    'treatmentAdvice' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'consultationRecommended' : IDL.Bool,
    'imageRef' : ExternalBlob,
    'timestamp' : Time,
    'severity' : Severity,
    'otcMedicines' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMedicalHistoryEntry' : IDL.Func([MedicalHistoryEntry], [], []),
    'analyze' : IDL.Func([ExternalBlob], [DiagnosticResult], []),
    'approveDoctor' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func([Appointment], [], []),
    'createOrUpdateDoctorProfile' : IDL.Func([DoctorProfile], [], []),
    'createOrUpdatePatientProfile' : IDL.Func([PatientProfile], [], []),
    'getAllDiagnoses' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(DiagnosisRecord)],
        ['query'],
      ),
    'getApprovedDoctors' : IDL.Func([], [IDL.Vec(DoctorProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(BasicPatientInfo)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalPatients' : IDL.Nat,
            'totalDiagnoses' : IDL.Nat,
            'emergencyCases' : IDL.Nat,
            'pendingDoctors' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getDiagnosisById' : IDL.Func([IDL.Text], [DiagnosisRecord], ['query']),
    'getDoctorAppointments' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getMedicalHistory' : IDL.Func(
        [],
        [IDL.Vec(MedicalHistoryEntry)],
        ['query'],
      ),
    'getOwnPatientProfile' : IDL.Func([], [PatientProfile], ['query']),
    'getPatientAppointments' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getPatientDiagnoses' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(DiagnosisRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BasicPatientInfo)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectDoctor' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([BasicPatientInfo], [], []),
    'submitDiagnosis' : IDL.Func([DiagnosisRecord], [], []),
    'updateDoctorNotes' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };