/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface DoctorProfile {
    bio: string;
    name: string;
    specialty: string;
    approved: boolean;
    availableSlots: Array<Time>;
    licenseNumber: string;
}
export interface BasicPatientInfo {
    age: bigint;
    bloodType?: string;
    name: string;
    gender: Gender;
    phone: string;
    existingConditions: Array<string>;
    allergies: Array<string>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MedicalHistoryEntry {
    notes: string;
    timestamp: Time;
}
export interface DiagnosisRecord {
    id: string;
    isEmergency: boolean;
    doctorNotes?: string;
    patientId: Principal;
    conditionName: string;
    treatmentAdvice: string;
    confidenceScore: bigint;
    consultationRecommended: boolean;
    imageRef: ExternalBlob;
    timestamp: Time;
    severity: Severity;
    otcMedicines: Array<string>;
}
export interface DiagnosticResult {
    isEmergency: boolean;
    conditionName: string;
    treatmentAdvice: string;
    confidenceScore: bigint;
    consultationRecommended: boolean;
    severity: Severity;
    otcMedicines: Array<string>;
}
export interface PatientProfile {
    info: BasicPatientInfo;
    medicalHistory: Array<MedicalHistoryEntry>;
}
export interface Appointment {
    doctorId: Principal;
    patientId: Principal;
    dateTime: Time;
    reason: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum Severity {
    low = "low",
    emergency = "emergency",
    high = "high",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMedicalHistoryEntry(entry: MedicalHistoryEntry): Promise<void>;
    analyze(imageRef: ExternalBlob): Promise<DiagnosticResult>;
    approveDoctor(doctorId: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookAppointment(appointment: Appointment): Promise<void>;
    createOrUpdateDoctorProfile(profile: DoctorProfile): Promise<void>;
    createOrUpdatePatientProfile(profile: PatientProfile): Promise<void>;
    getAllDiagnoses(start: bigint, end: bigint): Promise<Array<DiagnosisRecord>>;
    getApprovedDoctors(): Promise<Array<DoctorProfile>>;
    getCallerUserProfile(): Promise<BasicPatientInfo | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<{
        totalPatients: bigint;
        totalDiagnoses: bigint;
        emergencyCases: bigint;
        pendingDoctors: bigint;
    }>;
    getDiagnosisById(id: string): Promise<DiagnosisRecord>;
    getDoctorAppointments(start: bigint, end: bigint): Promise<Array<Appointment>>;
    getMedicalHistory(): Promise<Array<MedicalHistoryEntry>>;
    getOwnPatientProfile(): Promise<PatientProfile>;
    getPatientAppointments(start: bigint, end: bigint): Promise<Array<Appointment>>;
    getPatientDiagnoses(start: bigint, end: bigint): Promise<Array<DiagnosisRecord>>;
    getUserProfile(user: Principal): Promise<BasicPatientInfo | null>;
    isCallerAdmin(): Promise<boolean>;
    rejectDoctor(doctorId: Principal): Promise<void>;
    saveCallerUserProfile(profile: BasicPatientInfo): Promise<void>;
    submitDiagnosis(record: DiagnosisRecord): Promise<void>;
    updateDoctorNotes(diagnosisId: string, notes: string): Promise<void>;
}
import type { BasicPatientInfo as _BasicPatientInfo, DiagnosisRecord as _DiagnosisRecord, DiagnosticResult as _DiagnosticResult, ExternalBlob as _ExternalBlob, Gender as _Gender, MedicalHistoryEntry as _MedicalHistoryEntry, PatientProfile as _PatientProfile, Severity as _Severity, Time as _Time, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMedicalHistoryEntry(arg0: MedicalHistoryEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMedicalHistoryEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMedicalHistoryEntry(arg0);
            return result;
        }
    }
    async analyze(arg0: ExternalBlob): Promise<DiagnosticResult> {
        if (this.processError) {
            try {
                const result = await this.actor.analyze(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_DiagnosticResult_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyze(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_DiagnosticResult_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveDoctor(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveDoctor(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookAppointment(arg0: Appointment): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0);
            return result;
        }
    }
    async createOrUpdateDoctorProfile(arg0: DoctorProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateDoctorProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateDoctorProfile(arg0);
            return result;
        }
    }
    async createOrUpdatePatientProfile(arg0: PatientProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdatePatientProfile(to_candid_PatientProfile_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdatePatientProfile(to_candid_PatientProfile_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllDiagnoses(arg0: bigint, arg1: bigint): Promise<Array<DiagnosisRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDiagnoses(arg0, arg1);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDiagnoses(arg0, arg1);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedDoctors(): Promise<Array<DoctorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedDoctors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedDoctors();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<BasicPatientInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<{
        totalPatients: bigint;
        totalDiagnoses: bigint;
        emergencyCases: bigint;
        pendingDoctors: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDiagnosisById(arg0: string): Promise<DiagnosisRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getDiagnosisById(arg0);
                return from_candid_DiagnosisRecord_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDiagnosisById(arg0);
            return from_candid_DiagnosisRecord_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctorAppointments(arg0: bigint, arg1: bigint): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorAppointments(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorAppointments(arg0, arg1);
            return result;
        }
    }
    async getMedicalHistory(): Promise<Array<MedicalHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMedicalHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMedicalHistory();
            return result;
        }
    }
    async getOwnPatientProfile(): Promise<PatientProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnPatientProfile();
                return from_candid_PatientProfile_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnPatientProfile();
            return from_candid_PatientProfile_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientAppointments(arg0: bigint, arg1: bigint): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientAppointments(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientAppointments(arg0, arg1);
            return result;
        }
    }
    async getPatientDiagnoses(arg0: bigint, arg1: bigint): Promise<Array<DiagnosisRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientDiagnoses(arg0, arg1);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientDiagnoses(arg0, arg1);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<BasicPatientInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rejectDoctor(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectDoctor(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: BasicPatientInfo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_BasicPatientInfo_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_BasicPatientInfo_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitDiagnosis(arg0: DiagnosisRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDiagnosis(await to_candid_DiagnosisRecord_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDiagnosis(await to_candid_DiagnosisRecord_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDoctorNotes(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctorNotes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctorNotes(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BasicPatientInfo_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BasicPatientInfo): BasicPatientInfo {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_DiagnosisRecord_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiagnosisRecord): Promise<DiagnosisRecord> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_DiagnosticResult_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiagnosticResult): DiagnosticResult {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Gender_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_PatientProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientProfile): PatientProfile {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BasicPatientInfo]): BasicPatientInfo | null {
    return value.length === 0 ? null : from_candid_BasicPatientInfo_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isEmergency: boolean;
    conditionName: string;
    treatmentAdvice: string;
    confidenceScore: bigint;
    consultationRecommended: boolean;
    severity: _Severity;
    otcMedicines: Array<string>;
}): {
    isEmergency: boolean;
    conditionName: string;
    treatmentAdvice: string;
    confidenceScore: bigint;
    consultationRecommended: boolean;
    severity: Severity;
    otcMedicines: Array<string>;
} {
    return {
        isEmergency: value.isEmergency,
        conditionName: value.conditionName,
        treatmentAdvice: value.treatmentAdvice,
        confidenceScore: value.confidenceScore,
        consultationRecommended: value.consultationRecommended,
        severity: from_candid_Severity_n11(_uploadFile, _downloadFile, value.severity),
        otcMedicines: value.otcMedicines
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    isEmergency: boolean;
    doctorNotes: [] | [string];
    patientId: Principal;
    conditionName: string;
    treatmentAdvice: string;
    confidenceScore: bigint;
    consultationRecommended: boolean;
    imageRef: _ExternalBlob;
    timestamp: _Time;
    severity: _Severity;
    otcMedicines: Array<string>;
}): Promise<{
    id: string;
    isEmergency: boolean;
    doctorNotes?: string;
    patientId: Principal;
    conditionName: string;
    treatmentAdvice: string;
    confidenceScore: bigint;
    consultationRecommended: boolean;
    imageRef: ExternalBlob;
    timestamp: Time;
    severity: Severity;
    otcMedicines: Array<string>;
}> {
    return {
        id: value.id,
        isEmergency: value.isEmergency,
        doctorNotes: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.doctorNotes)),
        patientId: value.patientId,
        conditionName: value.conditionName,
        treatmentAdvice: value.treatmentAdvice,
        confidenceScore: value.confidenceScore,
        consultationRecommended: value.consultationRecommended,
        imageRef: await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.imageRef),
        timestamp: value.timestamp,
        severity: from_candid_Severity_n11(_uploadFile, _downloadFile, value.severity),
        otcMedicines: value.otcMedicines
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bloodType: [] | [string];
    name: string;
    gender: _Gender;
    phone: string;
    existingConditions: Array<string>;
    allergies: Array<string>;
}): {
    age: bigint;
    bloodType?: string;
    name: string;
    gender: Gender;
    phone: string;
    existingConditions: Array<string>;
    allergies: Array<string>;
} {
    return {
        age: value.age,
        bloodType: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.bloodType)),
        name: value.name,
        gender: from_candid_Gender_n29(_uploadFile, _downloadFile, value.gender),
        phone: value.phone,
        existingConditions: value.existingConditions,
        allergies: value.allergies
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    info: _BasicPatientInfo;
    medicalHistory: Array<_MedicalHistoryEntry>;
}): {
    info: BasicPatientInfo;
    medicalHistory: Array<MedicalHistoryEntry>;
} {
    return {
        info: from_candid_BasicPatientInfo_n27(_uploadFile, _downloadFile, value.info),
        medicalHistory: value.medicalHistory
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    emergency: null;
} | {
    high: null;
} | {
    medium: null;
}): Severity {
    return "low" in value ? Severity.low : "emergency" in value ? Severity.emergency : "high" in value ? Severity.high : "medium" in value ? Severity.medium : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DiagnosisRecord>): Promise<Array<DiagnosisRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_DiagnosisRecord_n22(_uploadFile, _downloadFile, x)));
}
function to_candid_BasicPatientInfo_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BasicPatientInfo): _BasicPatientInfo {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_DiagnosisRecord_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiagnosisRecord): Promise<_DiagnosisRecord> {
    return await to_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Gender_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_PatientProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PatientProfile): _PatientProfile {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Severity_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): _Severity {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    info: BasicPatientInfo;
    medicalHistory: Array<MedicalHistoryEntry>;
}): {
    info: _BasicPatientInfo;
    medicalHistory: Array<_MedicalHistoryEntry>;
} {
    return {
        info: to_candid_BasicPatientInfo_n17(_uploadFile, _downloadFile, value.info),
        medicalHistory: value.medicalHistory
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    bloodType?: string;
    name: string;
    gender: Gender;
    phone: string;
    existingConditions: Array<string>;
    allergies: Array<string>;
}): {
    age: bigint;
    bloodType: [] | [string];
    name: string;
    gender: _Gender;
    phone: string;
    existingConditions: Array<string>;
    allergies: Array<string>;
} {
    return {
        age: value.age,
        bloodType: value.bloodType ? candid_some(value.bloodType) : candid_none(),
        name: value.name,
        gender: to_candid_Gender_n19(_uploadFile, _downloadFile, value.gender),
        phone: value.phone,
        existingConditions: value.existingConditions,
        allergies: value.allergies
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    isEmergency: boolean;
    doctorNotes?: string;
    patientId: Principal;
    conditionName: string;
    treatmentAdvice: string;
    confidenceScore: bigint;
    consultationRecommended: boolean;
    imageRef: ExternalBlob;
    timestamp: Time;
    severity: Severity;
    otcMedicines: Array<string>;
}): Promise<{
    id: string;
    isEmergency: boolean;
    doctorNotes: [] | [string];
    patientId: Principal;
    conditionName: string;
    treatmentAdvice: string;
    confidenceScore: bigint;
    consultationRecommended: boolean;
    imageRef: _ExternalBlob;
    timestamp: _Time;
    severity: _Severity;
    otcMedicines: Array<string>;
}> {
    return {
        id: value.id,
        isEmergency: value.isEmergency,
        doctorNotes: value.doctorNotes ? candid_some(value.doctorNotes) : candid_none(),
        patientId: value.patientId,
        conditionName: value.conditionName,
        treatmentAdvice: value.treatmentAdvice,
        confidenceScore: value.confidenceScore,
        consultationRecommended: value.consultationRecommended,
        imageRef: await to_candid_ExternalBlob_n8(_uploadFile, _downloadFile, value.imageRef),
        timestamp: value.timestamp,
        severity: to_candid_Severity_n37(_uploadFile, _downloadFile, value.severity),
        otcMedicines: value.otcMedicines
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Severity): {
    low: null;
} | {
    emergency: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Severity.low ? {
        low: null
    } : value == Severity.emergency ? {
        emergency: null
    } : value == Severity.high ? {
        high: null
    } : value == Severity.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
